### ISSUE TITLE
Adding support for non-static Mac entry

### ISSUE THREAD

**Issue by jediMunees** [Kmotiko/gofc#15]
NewOfpFlowModAddNonStatic() - Adding support for flow entry 'idle_timeout' second.

Pull request for review: #14

**Comment by Kmotiko** [comment]
Than you for your pull request @jediMunees .
I'll confirm your code.

**Comment by jediMunees** [comment]
It is already covered in IdleTimeout argument in NewOfpFlowModAdd existing gofc. So I am closing this issue.

**Comment by Kmotiko** [comment]
I'm sorry I didn't reply sooner @jediMunees , and thank you to close the issue. 

```
flowMessage = ofp13.NewOfpFlowModAdd(cookie, 0, 3, 9000, 0, match, instructions)
flowMessage.IdleTimeout = 120
dp.Send(flowMessage)
```

Yes, you can set IdleTimeout as described above.
On the other hand, I think that NewOfpFlowModAddNonStatic is the utility function to create FlowMod with timeout value.
I was thinking whether or not that is truly necessary.

**Comment by jediMunees** [comment]
Hi @Kmotiko , No worries. Thank you for your feedback. 

I thought the same as per your comment for NewOfpFlowModAddNonStatic(). I will continue to use as 'flowMessage.IdleTimeout = 120', if that utility function is not available.
