### ISSUE TITLE
Multicast ethernet mask issue

### ISSUE THREAD

**Issue by jediMunees** [Kmotiko/gofc#18]
@Kmotiko ,
Multicast ethernet mask's first octet is copied to all other octets due to hard-coded index. Added unit test and updated the code for the proposed fix.

OxmEth Serialize() is fixed to output the correct mask for multicast Ethernet.

Pull request for review: #17 

Please review it.

**Comment by Ipoola** [comment]
nice

**Comment by Kmotiko** [comment]
I merged your pull request #17 @jediMunees :)
Thank you for your contribution.

**Comment by jediMunees** [comment]
Issue is fixed with pull request #17 . So closing this issue. Thanks everyone.
