### ISSUE TITLE
Question about sample code 'gofc.go'

### ISSUE THREAD

**Issue by sangyun-han** [Kmotiko/gofc#22]
Hi, I'm sangyun who is interested in SDN, openflow things.
First of all, thank you for great project and your work.

I have met error for testing sample code.
In 'recvLoop' dp.conn.Read(buf) created 'failed to read conn' and 'EOF' error.
As I checked size, size is zero. I have the background of OpenFlow, but I'm a newbie about Golang.
why the sample code creates error? Am I something missing?

Thanks. 

p.s. please let me know a license of this project. If you write a license explicitly, can I use it?

**Comment by sangyun-han** [comment]
Oh, I found the license in README.

**Comment by Kmotiko** [comment]
Hi @sangyun-han 
Thank you for using my code and your question.

I can not solve your problem immediately, but I wan to be helpful to you.
Can you tell me your environment information ?
For example, OS, version of golang  and kind of openflow-switch.

> Oh, I found the license in README.

Sorry, I miss to put LICENSE text at this repository.
I'll append it.

**Comment by sangyun-han** [comment]
The environment of gofc is OS x(Mac OS) and openflow switch's environment is ubuntu-based virtual box in same mac os machine. They communicate each other by host-only adapter. I've tested gofc in linux machine. at that time, it was success. But only mac os has the problem. I will find a cause of the problem.
Thanks.

**Comment by sangyun-han** [comment]
I think "failed to read conn" and "EOF" message is created by OpenFlow switches's echo message.
When I turned off sending echo in 'HandleEchoRequest', these messages were generated again.

Best Regards,
Thank.

**Comment by Kmotiko** [comment]
Do you mean that gofc has bug in parsing process of EchoRequst ?
If you find bug, I would be happy if you tell me procedure to reproduce that problem.

Thank you,

**Comment by sangyun-han** [comment]
I don't know exactly. But if I find about it, let you know.

Thanks
