### ISSUE TITLE
Constructor definition policy is not consistent

### ISSUE THREAD

**Issue by Kmotiko** [Kmotiko/gofc#3]
The policy of constructor arguments is not coherent.
For example, NewOfpGroupMod, OfpGroupMod constructor, is defined as bellow.

```
type OfpGroupMod struct {
    Header  OfpHeader
    Command uint16
    Type    uint8
    Pad     uint8
    GroupId uint32
    Buckets []*OfpBucket
}

func NewOfpGroupMod(command uint16, t uint8, id uint32) *OfpGroupMod {
    header := NewOfpHeader(OFPT_GROUP_MOD)
    m := new(OfpGroupMod)
    m.Header = header
    m.Command = command
    m.Type = t
    m.GroupId = id
    m.Buckets = make([]*OfpBucket, 0)
    return m
}
```

This constructor has only two arguments, so does not take  parameter for Buckets which is slice of OfpBucket.
In this constructor, Buckets is initialized with empty slice.

But NewOfpPacketOut, constructor for OfpPacketOut is following.

```
type OfpPacketOut struct {
    Header    OfpHeader
    BufferId  uint32
    InPort    uint32
    ActionLen uint16
    Pad       [6]uint8
    Actions   []OfpAction
    Data      []byte
}

func NewOfpPacketOut(
    bufferId uint32,
    inPort uint32,
    actions []OfpAction,
    data []byte) *OfpPacketOut {
    header := NewOfpHeader(OFPT_PACKET_OUT)
    m := new(OfpPacketOut)
    m.Header = header
    m.BufferId = bufferId
    m.InPort = inPort
    if actions != nil {
        m.ActionLen = (uint16)(len(actions))
        m.Actions = actions
    } else {
        m.ActionLen = 0
        m.Actions = make([]OfpAction, 0)
    }
    m.Data = data
    return m
}
```

This constructor receive parameter for all of OfpPacketOut member, including slice type,  as arguments and create  instance with it.
In this process, gofc check whether  parameter "actions" is nil or not.
If actions is NOT nil, parameter is set to receiver's field, otherwise member will be initialized as empty slice.

This incoherent design is ugly, so it should be fixed.

**Comment by xgfone** [comment]
+1.

Additionally, see
```go
// ofp_queue_op_failed_code
const (
	OFPQOFC_BAD_PORT = iota
	OFPQQFC_BAD_QUEUE
	OFPQQFC_EPERM
)
```
It should be `OFPQOFC_BAD_QUEUE` and `OFPQOFC_EPERM`, not `OFPQQFC_BAD_QUEUE` and `OFPQQFC_EPERM`.

**Comment by Kmotiko** [comment]
Oh..Thanks for your comment, and sorry for late reply.
It is a typo...
I'll fix it in next commit.

**Comment by Kmotiko** [comment]
> @xgfone 

I treat the issue, which you reported, as another topic #5, 
because that problem is about typo and It differs from the contents of this issue.

**Comment by Kmotiko** [comment]
I merge pull request for this issue and #6 , so I close this.
