### ISSUE TITLE
Does datapath's send&recv goroutine duplicated?

### ISSUE THREAD

**Issue by gonotes** [Kmotiko/gofc#4]
Thanks for your grate work, it make openflow clean to understand!

In controller's code when session up , handleConnection has the fellowing code to setup datapath's send&recv goroutine:

`// create datapath`
`dp := NewDatapath(conn)`
`go dp.recvLoop()`
`go dp.sendLoop()`

However, in NewDatapath function itself,the  send&recv goroutine is already kicked:
`go dp.recvLoop()`
`go dp.sendLoop()`

is that a mistake or am i don't get it?

**Comment by Kmotiko** [comment]
I'm sorry for my late reply, and thank you for using my application.

It's embarrassing, but I think it is my mistake.
The send&recv goroutine is launched twice, but one is unnecessary. 
So I'll fix it with removing goroutine call in NewDatapath function.

**Comment by Kmotiko** [comment]
I remove goroutine statement in NewDatapath.
@gonotes, please check it and close this issue if it's ok.

**Comment by gonotes** [comment]
@Kmotiko Thank you 👍

**Comment by Kmotiko** [comment]
Thank you for confirmation. 
I'll close this issue.
