### ISSUE TITLE
Simplify the parameters of the function calling

### ISSUE THREAD

**Issue by xgfone** [Kmotiko/gofc#6]
For instance, `NewOfpFlowMod` has too many arguments and the user need to remember and write them, which is not a good experience.
```go
func NewOfpFlowMod(
	cookie uint64,
	cookieMask uint64,
	tableId uint8,
	command uint8,
	idleTimeout uint16,
	hardTimeout uint16,
	priority uint16,
	bufferId uint32,
	outPort uint32,
	outGroup uint32,
	flags uint16,
) {
// ......
}
```

I think, it should have the arguments as few as possible, then set the default value for other fields. If the user want a different value, he later can set it individually.

Lastly, the default value had better be the most common. So the user maybe reset the default value rarely.

What do you think?

**Comment by Kmotiko** [comment]
Thank your comment @xgfone .
I think that your opinion is not wrong.
At least, I think that design policy should be unified as mentiond in issue #3.

Some function, for example NewOfpFlowMod, has a lot of parameter, and sometimes it is not useful.
I want to set default value to those arguments, but golang syntax does not support it.
So now, some NewXX function, which create new struct instance,  take all of member value of that struct type.

It is easy to reduce parameter and to set default value to it in function process.
But, it is little difficult to decide which value have to be set as function argument and which one should be set automatically. 

Incidentally, this topic is concerned with #3.
That issue talk about the definition policy of NewXX functions. 
I'm considering how to fix it.

**Comment by Kmotiko** [comment]
@xgfone 
I create new pull request to fix this issue.
I'm glad If you confirm it.

**Comment by Kmotiko** [comment]
@xgfone 
I will merge #7 on October 23 in japan time.
Please let me know on October 22 if you have opinion.
